version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
