---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ha-homeassistant-io-v1-homeassistant
  failurePolicy: Fail
  name: vhomeassistant-v1.kb.io
  rules:
  - apiGroups:
    - ha.homeassistant.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - homeassistants
  sideEffects: None
