---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantareas
  - homeassistantautomations
  - homeassistantconfigurations
  - homeassistantfloors
  - homeassistantintegrations
  - homeassistantlabels
  - homeassistants
  - homeassistantscenes
  - homeassistantscripts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantareas/finalizers
  - homeassistantautomations/finalizers
  - homeassistantconfigurations/finalizers
  - homeassistantfloors/finalizers
  - homeassistantintegrations/finalizers
  - homeassistantlabels/finalizers
  - homeassistants/finalizers
  - homeassistantscenes/finalizers
  - homeassistantscripts/finalizers
  - homeassistantsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantareas/status
  - homeassistantautomations/status
  - homeassistantconfigurations/status
  - homeassistantfloors/status
  - homeassistantintegrations/status
  - homeassistantlabels/status
  - homeassistants/status
  - homeassistantscenes/status
  - homeassistantscripts/status
  - homeassistantsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
