---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantautomations
  - homeassistantconfigurations
  - homeassistants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantautomations/finalizers
  - homeassistantconfigurations/finalizers
  - homeassistants/finalizers
  - homeassistantsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantautomations/status
  - homeassistantconfigurations/status
  - homeassistants/status
  - homeassistantsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ha.homeassistant.io
  resources:
  - homeassistantsecrets
  verbs:
  - get
  - list
  - watch
