#!/usr/bin/env bash
# sync-chart-from-config.sh — regenerate the chart's STATIC parts from the
# authoritative config/ (Kustomize + controller-gen), so the Helm chart can never
# physically drift from Kustomize.
#
# Generated:
#   1) charts/**/crds/*.yaml          <- config/crd/bases/*.yaml (verbatim copy)
#   2) chart ClusterRole `rules:`     <- config/rbac/role.yaml .rules
#   3) chart leader-election `rules:` <- config/rbac/leader_election_role.yaml .rules
#
# Only the `rules:` block of the RBAC templates is generated; the Helm-templated
# header (metadata name/labels via _helpers.tpl) is preserved. Edit config/, then
# run `make helm-sync` — never hand-edit the generated regions.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
# shellcheck source=hack/lib-helm.sh
source "$ROOT/hack/lib-helm.sh"

YQ="$(hh_yq)"
CRD_SRC="config/crd/bases"
CRD_DST="${HELM_CHART_DIR}/crds"
CR_TMPL="${HELM_CHART_DIR}/templates/clusterrole.yaml"
ROLE_TMPL="${HELM_CHART_DIR}/templates/role.yaml"

banner="# GENERATED by hack/sync-chart-from-config.sh from config/crd/bases — DO NOT EDIT."

echo "==> Syncing CRDs: ${CRD_SRC} -> ${CRD_DST}"
# Refuse to proceed if there are no source CRDs — otherwise the cleanup below
# would wipe the chart's existing CRDs and leave nothing in their place.
shopt -s nullglob
crd_sources=("$CRD_SRC"/*.yaml)
shopt -u nullglob
[ "${#crd_sources[@]}" -gt 0 ] || { echo "❌ no CRD sources found in ${CRD_SRC}" >&2; exit 2; }
mkdir -p "$CRD_DST"
# Remove stale generated CRDs, then copy fresh with a generated banner.
find "$CRD_DST" -maxdepth 1 -name '*.yaml' -delete
for f in "${crd_sources[@]}"; do
  base="$(basename "$f")"
  { echo "$banner"; cat "$f"; } > "$CRD_DST/$base"
done

# sync_rules <template> <config-source>
# Keep everything up to and including the first `rules:` line, replace the rest
# with the .rules sequence extracted from the config source.
sync_rules() {
  local tmpl="$1" src="$2" tmp
  [ -f "$tmpl" ] || { echo "❌ missing template: $tmpl" >&2; exit 2; }
  [ -f "$src" ]  || { echo "❌ missing rbac source: $src" >&2; exit 2; }
  tmp="$(mktemp)"
  sed -n '1,/^rules:/p' "$tmpl" > "$tmp"
  echo "# GENERATED rules from ${src} — edit config/rbac, then run 'make helm-sync'." >> "$tmp"
  "$YQ" '.rules' "$src" >> "$tmp"
  mv "$tmp" "$tmpl"
}

echo "==> Syncing ClusterRole rules: config/rbac/role.yaml -> ${CR_TMPL}"
sync_rules "$CR_TMPL" "config/rbac/role.yaml"

echo "==> Syncing leader-election Role rules: config/rbac/leader_election_role.yaml -> ${ROLE_TMPL}"
sync_rules "$ROLE_TMPL" "config/rbac/leader_election_role.yaml"

echo "✅ chart synced from config/"
