apiVersion: ha.homeassistant.io/v1alpha1
kind: HomeAssistant
metadata:
  labels:
    app.kubernetes.io/name: homeassistant-operator
    app.kubernetes.io/managed-by: kustomize
  name: homeassistant-sample
spec:
  version: "stable"
  timezone: "Europe/Warsaw"
  storage:
    size: "5Gi"
  service:
    type: ClusterIP
    port: 8123
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
---
apiVersion: ha.homeassistant.io/v1alpha1
kind: HomeAssistantConfiguration
metadata:
  labels:
    app.kubernetes.io/name: homeassistant-operator
    app.kubernetes.io/managed-by: kustomize
  name: homeassistant-sample-config
spec:
  homeAssistantRef:
    name: homeassistant-sample
  configuration: |
    homeassistant:
      name: Home
      unit_system: metric

    # Enables the default set of integrations
    default_config:
