## Append samples of your project ##
resources:
- ha_v1alpha1_homeassistant.yaml
- ha_v1alpha1_homeassistantsecrets.yaml
- ha_v1alpha1_homeassistant_with_bootstrap.yaml
- ha_v1alpha1_homeassistant_with_config.yaml
- haconfig_hot_reload_strategy.yaml
- haconfig_restart_strategy.yaml
- complete_example_with_secrets.yaml
- ha_v1alpha1_gateway_api.yaml
- ha_v1alpha1_homeassistantintegration_mqtt.yaml
- ha_v1alpha1_homeassistantintegration_recorder.yaml
- ha_v1alpha1_homeassistantfloor.yaml
- ha_v1alpha1_homeassistantlabel.yaml
- ha_v1alpha1_homeassistantarea.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
