## Append samples of your project ##
resources:
- ha_v1alpha1_homeassistant.yaml
- ha_v1alpha1_homeassistantsecrets.yaml
- ha_v1alpha1_homeassistant_with_bootstrap.yaml
- ha_v1alpha1_homeassistant_with_config.yaml
- haconfig_hot_reload_strategy.yaml
- haconfig_restart_strategy.yaml
- complete_example_with_secrets.yaml
- ha_v1alpha1_homeassistantaddon_mosquitto.yaml
- ha_v1alpha1_homeassistantaddon_mariadb.yaml
- ha_v1alpha1_homeassistantaddon_nodered.yaml
- ha_v1alpha1_homeassistantaddon_custom.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
