name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test

      - name: Generate coverage report
        run: |
          go tool cover -html=cover.out -o coverage.html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./cover.out
          flags: unittests
          name: codecov-umbrella

      - name: Go Test Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          # The relative path to the test coverage file.
          profile: cover.out
          # The relative path to the html output file (optional)
          local-prefix: github.com/przemekhys/homeassistant-operator
          # Minimum code coverage percentage to pass the check
          threshold-file: 70
          # If the coverage is less than threshold, workflow will fail
          threshold-package: 70
          # Exclude files from coverage report
          # exclude-files: vendor
